/**
 * 医疗黄金标准模板知识库 (Template Knowledge Base)
 *
 * 经过物理微米级几何引擎与合规校验器验证的“黄金骨架 (Golden Skeletons)”。
 * 针对医院常见高频单据（血常规、生化全套、TEG 凝血、超声 PACS、门诊处方），
 * 提供预设最优的页边距、双列折流比例、患者信息字段组合与几何约束配置。
 */

import type { MedicalReportCategory } from './fingerprinter.js'

export interface GoldenArchetype {
  id: string
  name: string
  category: MedicalReportCategory
  paper_size: { width_mm: number; height_mm: number }
  margins: { top_mm: number; right_mm: number; bottom_mm: number; left_mm: number }
  description: string
  keywords: string[]
  template_skeleton: Record<string, unknown>
}

export const GOLDEN_ARCHETYPES: GoldenArchetype[] = [
  {
    id: 'lis_blood_routine_24_a5_snaking',
    name: '全血细胞分析 (血常规24项) A5 双列折流标准模板',
    category: 'LisBloodRoutine',
    paper_size: { width_mm: 210, height_mm: 148 },
    margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
    description: '国内三甲与基层通用的 A5 横向血常规 24 项化验单，双列折流平衡，条形码防伪与主管技师签名',
    keywords: ['血常规', '全血细胞', 'WBC', 'RBC', 'PLT', 'HGB', '白细胞', '红细胞', '血小板', '中性粒细胞'],
    template_skeleton: {
      id: 'lis_blood_routine_24_a5_snaking',
      name: '全血细胞分析 (血常规24项) 报告单',
      version: '1.0',
      app: 'MedPrint',
      report_type: 'LisBloodRoutine',
      paper_size: { width_mm: 210, height_mm: 148 },
      margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
      page_budget: 'SinglePageHard',
      elements: [
        {
          kind: 'HospitalHeader',
          hospital_name: '首都医科大学附属北京朝阳医院',
          sub_title: '检验医学科 / 临床血液实验室',
          report_title: '全血细胞分析 (血常规24项) 报告单',
          align: 'center',
          show_report_no: true,
          report_no_label: '检验单号',
          report_no_preview: 'LIS20260908001',
        },
        {
          kind: 'PatientBanner',
          include_barcode: true,
          fields: [
            { key: 'name', label: '姓名', preview_value: '张建国' },
            { key: 'gender', label: '性别', preview_value: '男' },
            { key: 'age', label: '年龄', preview_value: '42岁' },
            { key: 'inpatient_no', label: '病案号', preview_value: 'MR20260912' },
            { key: 'department', label: '科室', preview_value: '呼吸与危重症医学科' },
            { key: 'bed_no', label: '床号', preview_value: '18床' },
            { key: 'sample_type', label: '标本类型', preview_value: 'EDTA抗凝全血' },
          ],
        },
        {
          kind: 'SnakingTable',
          columns_count: 2,
          column_gap: 6.0,
          left_ratio: 0.5,
          items: [
            { index: 1, item_name: '白细胞计数', item_abbr: 'WBC', result_value: '6.52', unit: '10^9/L', ref_range_display: '3.50 - 9.50', alert_flag: 'Normal', is_critical: false },
            { index: 2, item_name: '红细胞计数', item_abbr: 'RBC', result_value: '4.85', unit: '10^12/L', ref_range_display: '4.30 - 5.80', alert_flag: 'Normal', is_critical: false },
            { index: 3, item_name: '血红蛋白测定', item_abbr: 'HGB', result_value: '152.0', unit: 'g/L', ref_range_display: '130.0 - 175.0', alert_flag: 'Normal', is_critical: false },
            { index: 4, item_name: '红细胞压积', item_abbr: 'HCT', result_value: '45.1', unit: '%', ref_range_display: '40.0 - 50.0', alert_flag: 'Normal', is_critical: false },
            { index: 5, item_name: '平均红细胞体积', item_abbr: 'MCV', result_value: '93.0', unit: 'fL', ref_range_display: '82.0 - 100.0', alert_flag: 'Normal', is_critical: false },
            { index: 6, item_name: '平均红细胞血红蛋白量', item_abbr: 'MCH', result_value: '31.3', unit: 'pg', ref_range_display: '27.0 - 34.0', alert_flag: 'Normal', is_critical: false },
            { index: 7, item_name: '平均红细胞血红蛋白浓度', item_abbr: 'MCHC', result_value: '337.0', unit: 'g/L', ref_range_display: '316.0 - 354.0', alert_flag: 'Normal', is_critical: false },
            { index: 8, item_name: '红细胞体积分布宽度-CV', item_abbr: 'RDW-CV', result_value: '12.4', unit: '%', ref_range_display: '11.5 - 14.5', alert_flag: 'Normal', is_critical: false },
            { index: 9, item_name: '血小板计数', item_abbr: 'PLT', result_value: '228.0', unit: '10^9/L', ref_range_display: '125.0 - 350.0', alert_flag: 'Normal', is_critical: false },
            { index: 10, item_name: '中性粒细胞百分比', item_abbr: 'NEUT%', result_value: '58.6', unit: '%', ref_range_display: '40.0 - 75.0', alert_flag: 'Normal', is_critical: false },
            { index: 11, item_name: '淋巴细胞百分比', item_abbr: 'LYMPH%', result_value: '31.2', unit: '%', ref_range_display: '20.0 - 50.0', alert_flag: 'Normal', is_critical: false },
            { index: 12, item_name: '单核细胞百分比', item_abbr: 'MONO%', result_value: '6.4', unit: '%', ref_range_display: '3.0 - 10.0', alert_flag: 'Normal', is_critical: false },
            { index: 13, item_name: '嗜酸性粒细胞百分比', item_abbr: 'EO%', result_value: '2.8', unit: '%', ref_range_display: '0.4 - 8.0', alert_flag: 'Normal', is_critical: false },
            { index: 14, item_name: '嗜碱性粒细胞百分比', item_abbr: 'BASO%', result_value: '0.5', unit: '%', ref_range_display: '0.0 - 1.0', alert_flag: 'Normal', is_critical: false },
            { index: 15, item_name: '中性粒细胞绝对值', item_abbr: 'NEUT#', result_value: '3.82', unit: '10^9/L', ref_range_display: '1.80 - 6.30', alert_flag: 'Normal', is_critical: false },
            { index: 16, item_name: '淋巴细胞绝对值', item_abbr: 'LYMPH#', result_value: '2.03', unit: '10^9/L', ref_range_display: '1.10 - 3.20', alert_flag: 'Normal', is_critical: false },
            { index: 17, item_name: '平均血小板体积', item_abbr: 'MPV', result_value: '10.2', unit: 'fL', ref_range_display: '9.0 - 13.0', alert_flag: 'Normal', is_critical: false },
            { index: 18, item_name: '血小板压积', item_abbr: 'PCT', result_value: '0.23', unit: '%', ref_range_display: '0.15 - 0.32', alert_flag: 'Normal', is_critical: false },
          ],
        },
        {
          kind: 'Seal',
          hospital_name: '首都医科大学附属北京朝阳医院',
          seal_title: '检验专用章',
          seal_code: 'LIS-QC-01',
          diameter_mm: 32.0,
          angle_jitter_deg: 1.5,
          opacity: 0.85,
          constraints: {
            anchor_position: 'BottomRight',
          },
        },
        {
          kind: 'Signatures',
          requesting_physician: '赵主任',
          sampling_person: '孙护士',
          operator: '王检验师',
          reviewer: '陈主管技师',
          report_date: '2026-09-15 10:30',
        },
        {
          kind: 'NotesFooter',
          text: '注：本报告仅对本次标本检验结果负责。若对化验结果有疑义，请在报告发布后 24 小时内向检验科提出复查申请。',
        },
      ],
    },
  },
  {
    id: 'lis_biochemistry_18_a5_snaking',
    name: '急诊临床生化综合检验 (18项) A5 双列折流标准模板',
    category: 'LisBiochemistry',
    paper_size: { width_mm: 210, height_mm: 148 },
    margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
    description: '涵盖肝功、肾功、电解质、血糖等指标的高频急诊生化报告单，具备异常值与危急值高亮',
    keywords: ['生化', '肝功', '肾功', 'ALT', 'AST', 'TBIL', 'CREA', 'BUN', 'GLU', '转氨酶', '胆红素', '肌酐'],
    template_skeleton: {
      id: 'lis_biochemistry_18_a5_snaking',
      name: '临床生化检验综合报告单',
      version: '1.0',
      app: 'MedPrint',
      report_type: 'LisBloodRoutine',
      paper_size: { width_mm: 210, height_mm: 148 },
      margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
      page_budget: 'SinglePageHard',
      elements: [
        {
          kind: 'HospitalHeader',
          hospital_name: '复旦大学附属中山医院',
          sub_title: '检验医学中心 / 生化实验室',
          report_title: '急诊临床生化检验报告单',
          align: 'center',
          show_report_no: true,
          report_no_label: '样本编号',
          report_no_preview: 'BIO-2026-0988',
        },
        {
          kind: 'PatientBanner',
          include_barcode: true,
          fields: [
            { key: 'name', label: '姓名', preview_value: '李晓明' },
            { key: 'gender', label: '性别', preview_value: '女' },
            { key: 'age', label: '年龄', preview_value: '56岁' },
            { key: 'inpatient_no', label: '住院号', preview_value: 'ZY889021' },
            { key: 'department', label: '申请科室', preview_value: '消化内科' },
            { key: 'bed_no', label: '床号', preview_value: '05床' },
          ],
        },
        {
          kind: 'SnakingTable',
          columns_count: 2,
          column_gap: 6.0,
          left_ratio: 0.5,
          items: [
            { index: 1, item_name: '丙氨酸氨基转移酶', item_abbr: 'ALT', result_value: '68.5', unit: 'U/L', ref_range_display: '9.0 - 50.0', alert_flag: 'High', is_critical: false },
            { index: 2, item_name: '天门冬氨酸氨基转移酶', item_abbr: 'AST', result_value: '52.0', unit: 'U/L', ref_range_display: '15.0 - 40.0', alert_flag: 'High', is_critical: false },
            { index: 3, item_name: '总胆红素', item_abbr: 'TBIL', result_value: '14.2', unit: 'umol/L', ref_range_display: '3.4 - 20.5', alert_flag: 'Normal', is_critical: false },
            { index: 4, item_name: '直接胆红素', item_abbr: 'DBIL', result_value: '4.8', unit: 'umol/L', ref_range_display: '0.0 - 6.8', alert_flag: 'Normal', is_critical: false },
            { index: 5, item_name: '血清肌酐', item_abbr: 'CREA', result_value: '78.0', unit: 'umol/L', ref_range_display: '44.0 - 97.0', alert_flag: 'Normal', is_critical: false },
            { index: 6, item_name: '尿素氮', item_abbr: 'BUN', result_value: '5.6', unit: 'mmol/L', ref_range_display: '2.8 - 7.2', alert_flag: 'Normal', is_critical: false },
            { index: 7, item_name: '葡萄糖', item_abbr: 'GLU', result_value: '16.8', unit: 'mmol/L', ref_range_display: '3.90 - 6.10', alert_flag: 'Critical', is_critical: true },
            { index: 8, item_name: '血清钾', item_abbr: 'K', result_value: '4.15', unit: 'mmol/L', ref_range_display: '3.50 - 5.30', alert_flag: 'Normal', is_critical: false },
            { index: 9, item_name: '血清钠', item_abbr: 'Na', result_value: '141.0', unit: 'mmol/L', ref_range_display: '137.0 - 147.0', alert_flag: 'Normal', is_critical: false },
            { index: 10, item_name: '血清氯', item_abbr: 'Cl', result_value: '102.0', unit: 'mmol/L', ref_range_display: '99.0 - 110.0', alert_flag: 'Normal', is_critical: false },
          ],
        },
        {
          kind: 'Seal',
          hospital_name: '复旦大学附属中山医院',
          seal_title: '检验科专用章',
          seal_code: 'SEAL-ZS-02',
          diameter_mm: 32.0,
          angle_jitter_deg: 2.0,
          opacity: 0.85,
        },
        {
          kind: 'Signatures',
          requesting_physician: '刘副主任',
          operator: '张检验技师',
          reviewer: '马主管检验师',
          report_date: '2026-09-15 09:15',
        },
        {
          kind: 'NotesFooter',
          text: '注：GLU 达到危急值阈值（>15.0 mmol/L），已于 09:20 电话通报病区责任护士。',
        },
      ],
    },
  },
  {
    id: 'teg_hemostasis_a5',
    name: '血栓弹力图 (TEG) 凝血功能专项报告 A5 避让折流模板',
    category: 'TegThromboelastogram',
    paper_size: { width_mm: 210, height_mm: 148 },
    margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
    description: '包含 TEG 曲线图（空间障碍物）与凝血六项参数表（自适应绕开避让）的标准报告单',
    keywords: ['血栓弹力图', 'TEG', '凝血', 'R', 'K', 'Angle', 'MA', 'LY30', 'CI', '弹力图'],
    template_skeleton: {
      id: 'teg_hemostasis_a5',
      name: '血栓弹力图 (TEG) 凝血功能专项报告单',
      version: '1.0',
      app: 'MedPrint',
      report_type: 'TegThromboelastogram',
      paper_size: { width_mm: 210, height_mm: 148 },
      margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
      page_budget: 'SinglePageHard',
      elements: [
        {
          kind: 'HospitalHeader',
          hospital_name: '中日友好医院',
          sub_title: '输血科 / 围术期凝血监测室',
          report_title: '血栓弹力图 (TEG) 检验报告单',
          align: 'center',
          show_report_no: true,
          report_no_label: '检测流水号',
          report_no_preview: 'TEG-2026-778',
        },
        {
          kind: 'PatientBanner',
          include_barcode: true,
          fields: [
            { key: 'name', label: '姓名', preview_value: '王秀兰' },
            { key: 'gender', label: '性别', preview_value: '女' },
            { key: 'age', label: '年龄', preview_value: '67岁' },
            { key: 'inpatient_no', label: '病案号', preview_value: 'ZR109283' },
            { key: 'department', label: '手术科室', preview_value: '心胸外科' },
          ],
        },
        {
          kind: 'TegCurveChart',
          constraints: {
            obstacle_constraint: {
              is_obstacle: true,
              safe_padding_mm: 5.0,
              flow_behavior: 'AvoidAndNarrow',
            },
          },
        },
        {
          kind: 'SnakingTable',
          columns_count: 1,
          column_gap: 4.0,
          left_ratio: 1.0,
          items: [
            { index: 1, item_name: '凝血反应时间 (R)', item_abbr: 'R', result_value: '5.2', unit: 'min', ref_range_display: '4.0 - 8.0', alert_flag: 'Normal', is_critical: false },
            { index: 2, item_name: '凝血形成时间 (K)', item_abbr: 'K', result_value: '1.8', unit: 'min', ref_range_display: '1.0 - 3.0', alert_flag: 'Normal', is_critical: false },
            { index: 3, item_name: '凝固角 (α角)', item_abbr: 'Angle', result_value: '66.5', unit: 'deg', ref_range_display: '53.0 - 72.0', alert_flag: 'Normal', is_critical: false },
            { index: 4, item_name: '最大振幅 (MA)', item_abbr: 'MA', result_value: '63.8', unit: 'mm', ref_range_display: '50.0 - 70.0', alert_flag: 'Normal', is_critical: false },
            { index: 5, item_name: '30分钟纤溶指数', item_abbr: 'LY30', result_value: '2.1', unit: '%', ref_range_display: '0.0 - 7.5', alert_flag: 'Normal', is_critical: false },
            { index: 6, item_name: '凝血综合指数 (CI)', item_abbr: 'CI', result_value: '+1.2', unit: '', ref_range_display: '-3.0 - +3.0', alert_flag: 'Normal', is_critical: false },
          ],
        },
        {
          kind: 'Signatures',
          requesting_physician: '钱主任',
          operator: '孙检验师',
          reviewer: '周主管技师',
          report_date: '2026-09-15 11:20',
        },
        {
          kind: 'Seal',
          hospital_name: '中日友好医院',
          seal_title: '输血检测专用章',
          seal_code: 'TEG-01',
          diameter_mm: 30.0,
          angle_jitter_deg: 1.0,
          opacity: 0.85,
        },
      ],
    },
  },
  {
    id: 'pacs_ultrasound_doppler_a4',
    name: '彩色多普勒超声检查报告 A4 图文诊断标准模板',
    category: 'PacsImaging',
    paper_size: { width_mm: 210, height_mm: 297 },
    margins: { top_mm: 12, right_mm: 12, bottom_mm: 12, left_mm: 12 },
    description: '包含 2x2 超声 DICOM 切面网格、超声所见（叙述描述）与超声提示（结构化诊断）的标准 A4 报告',
    keywords: ['超声', '彩超', '多普勒', '超声所见', '超声提示', '探头', '回声', '结节', '囊肿'],
    template_skeleton: {
      id: 'pacs_ultrasound_doppler_a4',
      name: '彩色多普勒超声检查报告单',
      version: '1.0',
      app: 'MedPrint',
      report_type: 'PacsImagingReport',
      paper_size: { width_mm: 210, height_mm: 297 },
      margins: { top_mm: 12, right_mm: 12, bottom_mm: 12, left_mm: 12 },
      page_budget: 'SinglePageHard',
      elements: [
        {
          kind: 'HospitalHeader',
          hospital_name: '华中科技大学同济医学院附属同济医院',
          sub_title: '医学超声科',
          report_title: '彩色多普勒超声检查报告单',
          align: 'center',
          show_report_no: true,
          report_no_label: '检查号',
          report_no_preview: 'US2026-9901',
        },
        {
          kind: 'PatientBanner',
          include_barcode: true,
          fields: [
            { key: 'name', label: '姓名', preview_value: '林芳' },
            { key: 'gender', label: '性别', preview_value: '女' },
            { key: 'age', label: '年龄', preview_value: '35岁' },
            { key: 'department', label: '申请科室', preview_value: '甲状腺乳腺外科' },
            { key: 'inpatient_no', label: '门诊号', preview_value: 'MZ981273' },
          ],
        },
        {
          kind: 'PacsGrid',
          rows: 2,
          cols: 2,
        },
        {
          kind: 'Signatures',
          requesting_physician: '黄主治',
          operator: '吴超声医师',
          reviewer: '郑主任医师',
          report_date: '2026-09-15 14:00',
        },
        {
          kind: 'Seal',
          hospital_name: '同济医院',
          seal_title: '超声诊断专用章',
          seal_code: 'US-TJ-01',
          diameter_mm: 32.0,
          angle_jitter_deg: 0.8,
          opacity: 0.85,
        },
      ],
    },
  },
  {
    id: 'prescription_outpatient_a5',
    name: '医疗机构门诊处方笺 A5 标准规范模板',
    category: 'OutpatientPrescription',
    paper_size: { width_mm: 210, height_mm: 148 },
    margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
    description: '符合国家卫健委《处方管理办法》的 A5 横向处方笺，含 Rp 药品明细与四方签字链（医师/调配/核对/发药）',
    keywords: ['处方', 'Rp', '门诊处方', '处方笺', '药品', '口服', '用法用量', '药师'],
    template_skeleton: {
      id: 'prescription_outpatient_a5',
      name: '医疗机构门诊处方笺',
      version: '1.0',
      app: 'MedPrint',
      report_type: 'OutpatientPrescription',
      paper_size: { width_mm: 210, height_mm: 148 },
      margins: { top_mm: 8, right_mm: 10, bottom_mm: 8, left_mm: 10 },
      page_budget: 'SinglePageHard',
      elements: [
        {
          kind: 'HospitalHeader',
          hospital_name: '北京大学第一医院',
          sub_title: '普通门诊',
          report_title: '门诊处方笺',
          align: 'center',
          show_report_no: true,
          report_no_label: '处方编号',
          report_no_preview: 'RX20260915-01',
        },
        {
          kind: 'PatientBanner',
          include_barcode: true,
          fields: [
            { key: 'name', label: '姓名', preview_value: '赵敏' },
            { key: 'gender', label: '性别', preview_value: '女' },
            { key: 'age', label: '年龄', preview_value: '29岁' },
            { key: 'department', label: '门诊科室', preview_value: '呼吸内科门诊' },
          ],
        },
        {
          kind: 'Signatures',
          requesting_physician: '杨主治医师',
          operator: '李调配药师',
          reviewer: '张复核/发药药师',
          report_date: '2026-09-15 15:30',
        },
      ],
    },
  },
]
